// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB76vacIw6sM-bPWJ5AbocEibRZgiB6ejE',
    appId: '1:99264897779:web:833cd318c0e1dc1cc98d86',
    messagingSenderId: '99264897779',
    projectId: 'pwith-e04d4',
    authDomain: 'pwith-e04d4.firebaseapp.com',
    storageBucket: 'pwith-e04d4.appspot.com',
    measurementId: 'G-HRVBH8Y0YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Rz54FeRp1QoUu5F4bNO2aN_p2l7tCHs',
    appId: '1:99264897779:android:1c595e036ed2405fc98d86',
    messagingSenderId: '99264897779',
    projectId: 'pwith-e04d4',
    storageBucket: 'pwith-e04d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaq8IfS8q0iOLxncGNt1C2z2IGwlx1S10',
    appId: '1:99264897779:ios:28230e4163fe0ec8c98d86',
    messagingSenderId: '99264897779',
    projectId: 'pwith-e04d4',
    storageBucket: 'pwith-e04d4.appspot.com',
    iosBundleId: 'com.dh.pwith',
  );

}